### ISSUE TITLE
Add alternative command and indexing (instead of random)

### ISSUE THREAD

**Issue by skeith** [ScarletRav3n/Scarlet-Cogs#1]
Please add `[p]kao` as alternative without using `[p]alias`

Also instead of always calling a random kaomoji, allow optional parameter to call a specific kaomoji, maybe like `[p]kao happy 7` return a kaomoji from happy category at index number 7. If the index is out of bound, output table flip kaomoji

**Comment by ScarletRav3n** [comment]
All of these have been added.
- [p]kao
- [p]kaomoji <category> [number] is now a thing as well. So you can remember your favourite kaomojis.
