### ISSUE TITLE
Kaomoji specific broken

### ISSUE THREAD

**Issue by ScarletRav3n** [ScarletRav3n/Scarlet-Cogs#7]
!kaomoji <category> [n] doesn't work. Please fix

**Comment by skeith** [comment]
what? detail please

**Comment by ScarletRav3n** [comment]
Say I put !kaomoji happy 5. It takes "happy 5" as a category and not separate entities.

**Comment by skeith** [comment]
Should be pretty easy. Because the old version has a working code for that
